EXTENTION = ssspeak

include ../common.mk

.dist-win32:: .force
	mv .dist-win32/ext/mbrola/mbrola.exe .dist-win32/ext/festival/lib/etc
.dist-linux:: .force
	mv .dist-linux/ext/mbrola/mbrola .dist-linux/ext/festival/lib/etc
