package org.nargila.speak.event.player;


/**
 * Event generated by player when it's Player.paused() method is called.
 * 
 * @author tshalif
 * @see org.nargila.speak.framework.player.Player#pause()
 */
public class PlayerPausedEvent extends PlayerEvent {	
	private static final long serialVersionUID = 1L;

	/**
	 * ctor
	 * @param source event generator (e.g. player) id 
	 */
	public PlayerPausedEvent(Object source) {
		super(source);
	}

	public String toString() {
		return "player paused";
	}
}
