package org.nargila.speak.event.player;

import org.nargila.speak.event.SpeakEvent;

/**
 * Player play pos offset event. An offset event 
 * is generated by the player when it reaches a predefined
 * byte position in audio play stream. This even can be monitored
 * by the synthesizer and translate it into a synthesizer mark event.
 * 
 * @author tshalif
 *
 */
public class PlayerOffsetEvent extends SpeakEvent {
	private static final long serialVersionUID = 1L;

	/**
	 * ctor 
	 * @param source event generator (e.g. player, synthesizer) id 
	 * @param offset play pos (in bytes) where this event was generated
	 */
	public PlayerOffsetEvent(Object source, long offset) {
		super(source, new Long(offset));
	}
	
	/**
	 * get offset.
	 * @return player event offset in bytes
	 */
	public long getOffset() {
		return ((Long)getData()).longValue();
	}

	public String toString() {
		return "player offset: " + getOffset();
	}
}
