package org.nargila.speak.event.player;


/**
 * Event generated by player when it is stopped.
 * 
 * @author tshalif
 */
public class PlayerStopEvent extends PlayerEvent {	
	private static final long serialVersionUID = 1L;


	/**
	 * ctor
	 * @param source event generator (e.g. player) id 
	 */
	public PlayerStopEvent(Object source) {
		super(source);
	}

	public String toString() {
		return "player stopped";
	}
}
