/**
 * events generated by the player subsystem
 */
package org.nargila.speak.event.player;

import org.nargila.speak.event.SpeakEvent;

/**
 * Base player subsystem event 
 * @author tshalif
 */
public abstract class PlayerEvent extends SpeakEvent {
	private static final long serialVersionUID = 1L;

	/**
	 * ctor
	 * @param source event generator (e.g. player) id 
	 */
	protected PlayerEvent(Object source) {
		this(source, null);
	}
	/**
	 * ctor 
	 * @param source event generator (e.g. player) id 
	 * @param data event data
	 */
	protected PlayerEvent(Object source, Object data) {
		super(source, data);
	}
}

