package org.nargila.speak.event.player;

import org.nargila.speak.event.SpeakEvent;

/**
 * Event generated by player uppon reception of a seek() request
 * @author tshalif
 *
 */
public class PlayerSeekEvent extends SpeakEvent {
	
	private static final long serialVersionUID = 1L;

	/**
	 * ctor 
	 * @param source event generator (e.g. player) id 
	 * @param offset new play pos (in bytes)
	 */
	public PlayerSeekEvent(Object source, long offset) {
		super(source, new Long(offset));
	}
	
	/**
	 * getter
	 * @return new audio byte offset 
	 */
	public long getOffset() {
		return ((Long)getData()).longValue();
	}

	public String toString() {
		return "player seek: " + getOffset();
	}
}
