package org.nargila.speak.event.player;


/**
 * Event generated by player when it is started.
 * 
 * @author tshalif
 */
public class PlayerStartEvent extends PlayerEvent {	
	private static final long serialVersionUID = 1L;

	/**
	 * ctor
	 * @param source event generator (e.g. player) id 
	 */
	public PlayerStartEvent(Object source) {
		super(source);
	}

	public String toString() {
		return "player started";
	}
}
