/**
 * speak events
 */
package org.nargila.speak.event;

import org.nargila.util.Event;

/**
 * Base event type generated by player, syhthesizer, etc.
 * @author tshalif
 *
 */
public abstract class SpeakEvent extends Event {

	private static final long serialVersionUID = 1L;
	/**
	 * ctor
	 * @param source event generator (e.g. player, synthesizer) id 
	 */
	protected SpeakEvent(Object source) {
		this(source, null);
	}
	
	/**
	 * ctor 
	 * @param source event generator (e.g. player, synthesizer) id 
	 * @param data event data
	 */
	protected SpeakEvent(Object source, Object data) {
		super(source, data);
	}
	
	/**
	 * pretty print this event
	 */
	public abstract String toString();
}
