/**
 * events generated by the synthesis subsystem
 */
package org.nargila.speak.event.synth;

import org.nargila.speak.event.SpeakEvent;

/**
 * Base synthesis subsystem event 
 * @author tshalif
 */
public abstract class SynthesizerEvent extends SpeakEvent {
	private static final long serialVersionUID = 1L;

	/**
	 * ctor
	 * @param source event generator (e.g. synthesizer) id 
	 */
	protected SynthesizerEvent(Object source) {
		this(source, null);
	}
	/**
	 * ctor 
	 * @param source event generator (e.g. synthesizer) id 
	 * @param data event data
	 */
	protected SynthesizerEvent(Object source, Object data) {
		super(source, data);
	}
}
