package org.nargila.speak.event.synth;

/**
 * Mark event generated by the synthesizer when predefined play pos is reached.
 * @author tshalif
 */
public class SynthesizerMarkEvent extends SynthesizerEvent {
	
	private static final long serialVersionUID = 1L;
	/**
	 * ctor 
	 * @param source event generator (e.g. synthesizer) id 
	 * @param mark the synthesis mark
	 */
	public SynthesizerMarkEvent(Object source, String mark) {
		super(source, mark);
	}
	
	/**
	 * get synthesizer mark
	 * @return the ssml mark corresponding to current play pos 
	 */
	public String getMark() {
		return (String)getData();
	}
	public String toString() {
		return "synthesizer mark: " + getMark();
	}
}
